name: zest
description: Zest Deck.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  provider: 6.0.3
  auto_route: 4.2.0
  http: 0.13.4
  hive: 2.2.3
  hive_flutter: 1.1.0
  uuid: 3.0.6
  crypto: 3.0.2
  auto_size_text: 3.0.0
  flutter_svg: 1.1.1+1
  wc_form_validators: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: 4.2.0
  build_runner: 2.1.11
  hive_generator: 1.1.3

flutter:
  uses-material-design: false
  generate: true
  assets:
    - assets/
  fonts:
    - family: nasalization
      fonts:
        - asset: fonts/nasalization-rg.otf

flutter_intl:
  enabled: true
